### ISSUE TITLE
Error when setting up for February 29th in a leap year

### ISSUE THREAD

**Issue by lamadaemon** [lamadaemon/myweeklyplanner-auto#1]
As the title says and here are the logs

```
Node.js v18.15.0
[INFO] Begin process
[INFO] Setting up CSRF Token: [Token Removed]
[INFO] Skipping 0(DOW) becuase no data is present!
[INFO] Skipping 2024-02-26 because they were gone ~ Yes Forever ~ Can't be controlled like a river never stop
[INFO] Skipping 2024-02-27 because you or sombody else already done the job.
[INFO] Skipping 3(DOW) becuase no data is present!
[INFO] Skipping 2024-02-29 because you or sombody else already done the job.
/usr/local/lib/node_modules/myweeklyplanner-auto/index.js:542
    if(mn > 1 && this.isLeapYear()) dayOfYear++;
                                             ^
TypeError: Assignment to constant variable.
    at Date.getDOY (/usr/local/lib/node_modules/myweeklyplanner-auto/index.js:542:46)
    at /usr/local/lib/node_modules/myweeklyplanner-auto/index.js:567:22
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
```

**Comment by lamadaemon** [comment]
Fixed in 6ad2cf9
